# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    container_name: django_web
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:

