# Use postgres/example user/password credentials
version: '3.1'
services:
  db_postgres_test:
    image: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "4040:5432"

    networks:
      - backend

volumes:
  postgres:

networks:
  backend: